name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - run: npm ci
      - run: npm run build
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Publish package
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
